export const FILTER_BY_CONTINENT = "FILTER_BY_CONTINENT";
export const FILTER_BY_ACTIVITY = "FILTER_BY_ACTIVITY";
export const ORDER_BY_ALFABET = "ORDER_BY_ALFABET";
export const ORDER_BY_POBLATION = "ORDER_BY_POBLATION";
export const GET_COUNTRIES = "GET_COUNTRIES";
export const RESET_COUNTRIES = "RESET_COUNTRIES";